# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tunm/SoftWare/deploy_origin/cpp_implentation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tunm/SoftWare/deploy_origin/cpp_implentation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tunm/SoftWare/deploy_origin/cpp_implentation/CMakeFiles /home/tunm/SoftWare/deploy_origin/cpp_implentation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tunm/SoftWare/deploy_origin/cpp_implentation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named face_python_ext

# Build rule for target.
face_python_ext: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 face_python_ext
.PHONY : face_python_ext

# fast build rule for target.
face_python_ext/fast:
	$(MAKE) -f CMakeFiles/face_python_ext.dir/build.make CMakeFiles/face_python_ext.dir/build
.PHONY : face_python_ext/fast

ModelLoader.o: ModelLoader.cpp.o

.PHONY : ModelLoader.o

# target to build an object file
ModelLoader.cpp.o:
	$(MAKE) -f CMakeFiles/face_python_ext.dir/build.make CMakeFiles/face_python_ext.dir/ModelLoader.cpp.o
.PHONY : ModelLoader.cpp.o

ModelLoader.i: ModelLoader.cpp.i

.PHONY : ModelLoader.i

# target to preprocess a source file
ModelLoader.cpp.i:
	$(MAKE) -f CMakeFiles/face_python_ext.dir/build.make CMakeFiles/face_python_ext.dir/ModelLoader.cpp.i
.PHONY : ModelLoader.cpp.i

ModelLoader.s: ModelLoader.cpp.s

.PHONY : ModelLoader.s

# target to generate assembly for a file
ModelLoader.cpp.s:
	$(MAKE) -f CMakeFiles/face_python_ext.dir/build.make CMakeFiles/face_python_ext.dir/ModelLoader.cpp.s
.PHONY : ModelLoader.cpp.s

pythonExt.o: pythonExt.cpp.o

.PHONY : pythonExt.o

# target to build an object file
pythonExt.cpp.o:
	$(MAKE) -f CMakeFiles/face_python_ext.dir/build.make CMakeFiles/face_python_ext.dir/pythonExt.cpp.o
.PHONY : pythonExt.cpp.o

pythonExt.i: pythonExt.cpp.i

.PHONY : pythonExt.i

# target to preprocess a source file
pythonExt.cpp.i:
	$(MAKE) -f CMakeFiles/face_python_ext.dir/build.make CMakeFiles/face_python_ext.dir/pythonExt.cpp.i
.PHONY : pythonExt.cpp.i

pythonExt.s: pythonExt.cpp.s

.PHONY : pythonExt.s

# target to generate assembly for a file
pythonExt.cpp.s:
	$(MAKE) -f CMakeFiles/face_python_ext.dir/build.make CMakeFiles/face_python_ext.dir/pythonExt.cpp.s
.PHONY : pythonExt.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... face_python_ext"
	@echo "... ModelLoader.o"
	@echo "... ModelLoader.i"
	@echo "... ModelLoader.s"
	@echo "... pythonExt.o"
	@echo "... pythonExt.i"
	@echo "... pythonExt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

